# Generated by Django 4.1.1 on 2022-10-07 00:24

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('comment_write', models.DateTimeField(auto_now_add=True)),
                ('comment_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comment_table',
            },
        ),
        migrations.CreateModel(
            name='TweetModel',
            fields=[
                ('write_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=256)),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='MODIFY DATE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tweet_img', models.ImageField(blank=True, default=None, null=True, upload_to='tweet')),
                ('profile_img', models.TextField()),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'tweet_table',
            },
        ),
    ]
